config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'

  resources :posts
  get 'contact/index'
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact/index.html.haml
%h1.center Contact

app/views/home/index.html.haml
%h1.center Home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Nicholas Caged
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = csrf_meta_tags
  %body
    #wrap
      %header.masthead
        / Carousel
        #myCarousel.carousel.slide
          / Indicators
          %ol.carousel-indicators
            %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
          .carousel-inner
            .item.active
              %img{:src => "/assets/pic1.jpg"}/
              .container
                .carousel-caption
                  %h2 pic1
                  %p
            .item
              %img{:src => "/assets/pic2.jpg"}/
              .container
                .carousel-caption
                  %h2 pic2
                  %p
            .item
              %img{:src => "/assets/pic3.jpg"}/
              .container
                .carousel-caption
                  %h2 pic3
                  %p
          / /.carousel-inner
          .logo Nicholas Caged
          / Controls
          %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
            %span.glyphicon.glyphicon-chevron-left
          %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
            %span.glyphicon.glyphicon-chevron-right
        / /.carousel
      / Fixed navbar
      #nav.navbar.navbar-custom.navbar-inverse.navbar-static-top
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .collapse.navbar-collapse
            %ul.nav.navbar-nav.nav-justified
              %li
                =link_to root_path do
                  %i.glyphicon.glyphicon-home
              %li
                =link_to posts_path(@posts) do
                  %i.glyphicon.glyphicon-pencil
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#section3"}
                  %i.glyphicon.glyphicon-book
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} Chap. 1
                  %li
                    %a{:href => "#"} Chap. 2
                  %li
                    %a{:href => "#"} Chap. 3
                  %li
                    %a{:href => "#"} Chap. 4
                  %li
                    %a{:href => "#"} Chap. 5
                  %li
                    %a{:href => "#"} Chap. 6
              / %li
              /   %a{:href => "#section4"} button4
              %li
                =link_to contact_index_path do
                  %i.glyphicon.glyphicon-user
          / /.nav-collapse
        / /.container
      / /.navbar
    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1.center Posts
/ - @posts.each do |post|
/   .btn.btn-default
/     =link_to post_path(post) do
/       %div.title= post.title
/       %div.content= post.content
/   %span= link_to 'Edit', edit_post_path(post)
/   %span= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

.center
  = link_to 'New Post', new_post_path
%article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        %p Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.
        %p Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.
        %p What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.
        %p A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.
        %p For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.
        %h2.section-heading The Final Frontier
        %p There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.
        %p There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.
        %blockquote The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.
        %p Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.
        %h2.section-heading Reaching for the Stars
        %p As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.
        %span.caption.text-muted To go places and do things that have never been done before – that’s what living is all about.
        %p Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.
        %p As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.
        %p
          Placeholder text by
          = succeed "." do
            %a{:href => "http://spaceipsum.com/"} Space Ipsum
          = succeed "." do
            %a{:href => "https://www.flickr.com/photos/nasacommons/"} NASA on The Commons

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Content:
  = @post.content

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path